### ISSUE TITLE
com.demo.aerospike.config.AerospikeConfig$1: Error 4, 0:0:0:0:0:0:0:1 3000: Parameter error

### ISSUE THREAD

**Issue by rajcspsg** [aerospike-community/spring-data-aerospike#349]
Hi,

I've simple spring-data-aerospike [project](https://github.com/rajcspsg/spring-data-aerospike-demo)

I've basic aerospike [configuration](https://github.com/rajcspsg/spring-data-aerospike-demo/blob/master/src/main/java/com/demo/aerospike/config/AerospikeConfig.java#L27-L55) and entity to persist [User](https://github.com/rajcspsg/spring-data-aerospike-demo/blob/master/src/main/java/com/demo/aerospike/entity/User.java).

When I run this [app](https://github.com/rajcspsg/spring-data-aerospike-demo/blob/master/src/main/java/com/demo/aerospike/app/MySpringDataAerospikeDemo.java) I get below error -

```
Exception in thread "main" com.demo.aerospike.config.AerospikeConfig$1: Error 4,1,0,30000,0,0,BB9020011AC4202 0:0:0:0:0:0:0:1 3000: Parameter error
	at com.demo.aerospike.config.AerospikeConfig.lambda$aerospikeTemplate$0(AerospikeConfig.java:56)
	at org.springframework.data.aerospike.core.BaseAerospikeTemplate.translateError(BaseAerospikeTemplate.java:195)
	at org.springframework.data.aerospike.core.AerospikeTemplate.doPersistAndHandleError(AerospikeTemplate.java:583)
	at org.springframework.data.aerospike.core.AerospikeTemplate.save(AerospikeTemplate.java:154)
	at org.springframework.data.aerospike.repository.support.SimpleAerospikeRepository.save(SimpleAerospikeRepository.java:54)
	at org.springframework.data.aerospike.repository.support.SimpleAerospikeRepository.saveAll(SimpleAerospikeRepository.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:599)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:163)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy25.saveAll(Unknown Source)
	at com.demo.aerospike.app.MySpringDataAerospikeDemo.main(MySpringDataAerospikeDemo.java:19)
```

**Comment by rajcspsg** [comment]
The issue is I'm using unixtime when the unixtime for expiration is false.
